### ISSUE TITLE
Clarify label for "Show Signup on Checkout"

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-mailpoet#1]
It says selected "below", but the list is above. We can either move the option to the top of just change the word to "above".
![image](https://cloud.githubusercontent.com/assets/1254870/10077083/c37da85c-62ac-11e5-86e8-4d38ebb169bc.png)

**Comment by pippinsplugins** [comment]
:+1:

**Comment by pippinsplugins** [comment]
@mindctrl version bump and deploy at will!
