### ISSUE TITLE
Opt-in confirmations get sent for each item quantity in the cart

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-mailpoet#3]
When item quantities are enabled, the confirmation email is sent for each quantity in the cart. If you have Item A x 3 qty, you get three confirmation messages.

[Reported here](https://secure.helpscout.net/conversation/140349296/21563/?folderId=180499) and replicated locally.

**Comment by pippinsplugins** [comment]
@mindctrl Awesome. Deploy at will!
