### ISSUE TITLE
subscribers not added

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-mailpoet#5]
Both global and per-product, it appears that subscribers are not being added to the lists in MailPoet. Reported by a user. I've confirmed on my local install and so has @mintplugins.

**Comment by pippinsplugins** [comment]
@SDavisMedia Did I see you mention this was a false alarm or still valid?

**Comment by SDavisMedia** [comment]
Me saying it was a false alarm was a false alarm. Phil didn't test until after that and then after his confirmation, I created this issue. So still valid.

**Comment by pippinsplugins** [comment]
K. I'm going to work on this later this week.

**Comment by pippinsplugins** [comment]
Scratch that, early next.

**Comment by mindctrl** [comment]
I just tested global and per-product and they both worked for me separately. Was your email address already subscribed to another list? @SDavisMedia

**Comment by SDavisMedia** [comment]
@mindctrl Yup. Let me remove the account from the second list and try again.

**Comment by SDavisMedia** [comment]
@mindctrl Okay I did two tests. Different results.

* I tried again with an account that was already subscribed to another list. No luck. I then unsubscribed that account from the list it was on (which appears to stay somewhat connected to the dropped list afterwards) and tried once more. Still no luck.

* I completed a purchase with a fake email that has never been on a MailPoet list. It worked.

--

Can you confirm that behavior? Cc: @mintplugins

**Comment by mindctrl** [comment]
@SDavisMedia does it work if you delete the account instead of unsubscribe?

**Comment by SDavisMedia** [comment]
That's not even working, unfortunately. Bulk edit, that is.

Okay after more testing, it appears that it will not add a customer to the list unless they are brand new to the MailPoet system. That's the only time I can get it to work. 

Note that when someone unsubscribes from a list (admin manually unsubscribes them), the subscriber is still associated with that list in some way: http://glui.me/?i=d9nfc5mxl7z019h/2016-02-18_at_8.49_AM.png/

Maybe that has something to do with it. To recap, customers don't get added to lists unless MailPoet has never encountered that account before.

**Comment by mindctrl** [comment]
@SDavisMedia ok, in https://github.com/easydigitaldownloads/edd-mailpoet/issues/3 we set it to only add someone if they're not already on the list, due to them getting multiple emails with quantities enabled. We'll need to rethink that a little and just check against the current list I think.

**Comment by pippinsplugins** [comment]
I think we definitely need to allow them to be subscribed to separate lists. @mindctrl think you could work that up?

**Comment by SDavisMedia** [comment]
We should get some traction on this next week if possible.

**Comment by pippinsplugins** [comment]
@cklosowski @mindctrl  could you two please make this happen?

**Comment by mindctrl** [comment]
@cklosowski issue in #3 is back, where they get multiple confirmation emails if quantities are enabled. Otherwise looks good here.

**Comment by cklosowski** [comment]
interesting, ok I'll see if I can figure that out.

**Comment by SDavisMedia** [comment]
@cklosowski looking good here for this issue :+1:

**Comment by cklosowski** [comment]
@SDavisMedia can you test again? Just made a quick update to try and fix @mindctrl's issue with the quantities

**Comment by mindctrl** [comment]
@cklosowski looks good now!

**Comment by SDavisMedia** [comment]
@cklosowski just now setting this. All good?

**Comment by cklosowski** [comment]
Yep We're good.
