### ISSUE TITLE
MailPoet 3 Compatibility

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-mailpoet#9]
[MailPoet 3](https://wordpress.org/plugins/mailpoet/) is out, but its users can still use MailPoet 2. They're both available on .org. Our extension is compatible with MailPoet 2. MailPoet 3 does not look promising right now. Below is a list of things I find that have to happen to be compatible with MailPoet 3.

- [x] MailPoet lists do not populate in our setting for selecting a global list: https://cl.ly/2M133T2C0W3I that's a big one 😳 
- [x] MailPoet lists do not populate on product edit screens: https://cl.ly/082G3E2v1b15 this one too :flushed:

**Comment by SDavisMedia** [comment]
New ticket: https://secure.helpscout.net/conversation/428448362/66378/

**Comment by brashrebel** [comment]
Another ticket: https://secure.helpscout.net/conversation/441258706/67644/?folderId=180499

**Comment by SDavisMedia** [comment]
Played around with MailPoet 2 + our extension once again just to see what was and wasn't working. Everything seems fine except I can get emails to send. Not sure why. But just wanted to check on behavior before testing MailPoet 3. Gonna do that now.

**Comment by SDavisMedia** [comment]
Adjusting issue title and first post to use this issue as a checklist for making our extension compatible with MailPoet 3.

**Comment by SDavisMedia** [comment]
The two items in the checklist pretty much stop all testing. Our extension doesn't recognize MailPoet 3 lists at all. Can't go any further.

**Comment by pippinsplugins** [comment]
I've sent an email to MailPoet asking for a guide on how to migrate to the new version. Everything is completely different now.

**Comment by pippinsplugins** [comment]
@SDavisMedia PR ready for testing!

**Comment by SDavisMedia** [comment]
I'll get it tested today.

**Comment by SDavisMedia** [comment]
Those two listed issues are taken care of for me. So that's working.

I tested a logged out purchase with Auto Register and ran into these errors:

```
Notice: Trying to get property of non-object in /app/public/wp-content/plugins/edd-mailpoet/includes/class-edd-mailpoet.php on line 146

WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') WHERE l.`is_enabled` = 1 GROUP BY `user_id`' at line 10]
SELECT `user_id`, GROUP_CONCAT(ul.`list_id`) AS `lists` FROM `wp_wysija_user_list` ul JOIN `wp_wysija_list` l ON l.`list_id` = ul.`list_id` AND ul.`user_id` IN () WHERE l.`is_enabled` = 1 GROUP BY `user_id`

Notice: Trying to get property of non-object in /app/public/wp-content/plugins/edd-mailpoet/includes/class-edd-mailpoet.php on line 147
```

I am _not_ getting these errors with Auto Register disabled and just registering at checkout using the registration form.

However, in both scenarios (registering with Auto Register and registering manually), it does not appear that email addresses are being added to the MailPoet lists at all. Completing a purchase while already logged in is working fine. It's just not working when registration is happening at checkout.

**Comment by pippinsplugins** [comment]
@SDavisMedia I just retested with Auto Register and could not replicate that. I purchased products that had no product-specific lists and ones that did. I also tested logged in and logged out.

Could you try one more time and tell me it if it happens again?

**Comment by SDavisMedia** [comment]
@pippinsplugins I can't replicate on another computer, which is actually my primary workstation. FWIW, the data on my other computer is sketchy at times.

I just tested it all again several times on this computer and everything seems perfectly fine. This is the computer that also went through MailPoet's upgrade routine. So that's good.
